export const products = [
  {
    id: "ridge",
    number: "01",
    name: "Chaqueta Ridge",
    shortName: "Chaqueta",
    category: "Capa exterior",
    image: "/images/jacket.jpeg",
    alt: "Chaqueta marrón oliva con capucha y detalles de camuflaje en los hombros",
    width: 896,
    height: 1200,
    color: "Oliva",
    headline: "Hecha para seguirte.",
    description:
      "Una silueta amplia, tonos de montaña y detalles que invitan a mirar de cerca. La pieza que da forma a esta colección.",
    details: [
      ["Diseño exterior", "Acabado marrón oliva con paneles de camuflaje sobre los hombros y capucha integrada."],
      ["Ajuste y silueta", "Corte amplio, cierre frontal y puños con ajuste visible. Una propuesta para vestir en capas."],
      ["Bolsillos y acabados", "Bolsillos frontales, cierres verticales y un bolsillo en la manga completan el diseño."],
    ],
    point: { x: 54, y: 35 },
  },
  {
    id: "line",
    number: "02",
    name: "Pantalón Line",
    shortName: "Pantalón",
    category: "La siguiente capa",
    image: "/images/pants.jpeg",
    alt: "Pantalón de nieve color carbón con bolsillos laterales y costuras en las rodillas",
    width: 896,
    height: 1200,
    color: "Carbón",
    headline: "Tu línea. Tu movimiento.",
    description:
      "El contrapunto oscuro de la colección. Una silueta de líneas limpias con el protagonismo en la forma y los detalles.",
    details: [
      ["Diseño exterior", "Color carbón, pernera recta y paneles definidos por las costuras de la rodilla."],
      ["Cintura y silueta", "Cintura con trabillas y cierre frontal visible. El corte acompaña la silueta amplia de la chaqueta."],
      ["Bolsillos y acabados", "Bolsillos laterales de estilo cargo y cierres discretos en la parte superior."],
    ],
    point: { x: 53, y: 56 },
  },
  {
    id: "vision",
    number: "03",
    name: "Gafas Vision",
    shortName: "Gafas",
    category: "Otra perspectiva",
    image: "/images/glasses.jpeg",
    alt: "Gafas de nieve con lente azul reflectante, montura oscura y correa negra",
    width: 1024,
    height: 1024,
    color: "Azul / Grafito",
    headline: "Todo empieza en tu mirada.",
    description:
      "Azul glaciar sobre una montura oscura. La última pieza de un conjunto que encuentra su lugar entre la nieve y la montaña.",
    details: [
      ["Lente y color", "Lente azul reflectante de superficie curva. El color aporta contraste a los tonos neutros del conjunto."],
      ["Montura", "Montura oscura de contorno definido, con un apoyo central de formas suaves."],
      ["Correa y acabados", "Correa negra texturizada con uniones laterales integradas en el diseño."],
    ],
    point: { x: 54, y: 24 },
  },
];
